import { nanoid } from "nanoid";

export default {
    namespaced: true,
    state: {
        bookList: [
            {
                bookId: 1,
                bookName: "XX",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "XXX",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "XX",
                bookType: "X",
                bookPrice: 10,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 5,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 5,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 5,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 5,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 5,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 5,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 100,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 111,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 11,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 40,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 35,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 20,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
            {
                bookId: 1,
                bookName: "X",
                bookType: "X",
                bookPrice: 123,
                author: "X",
                description: "X",
                uploadTime: "X",
                uploadUser: "X",
            },
        ],
        bookTypeList: [
            "任意类型",
            "马克思主义著作",
            "哲学",
            "社会科学",
            "自然科学",
            "综合性图书",
        ],
    },
    actions: {
        addBookType(context, value) {
            /**
             * 此处向后端请求数据
             */
            const newData = {
                bookId: nanoid(),
                ...value
            };
            if (value && value !== "") {
                context.ADD_BOOKTYPELIST(newData);
            }
        },
        addBook(context, value) {
            /**
             * 此处向后端请求数据
             */
            const newData = {
                bookId: nanoid(),
                ...value
            };
            if (value && value !== "") {
                context.ADD_BOOK(newData);
            }
        }
    },
    mutations: {
        ADD_BOOKTYPE(state, value) {
            state.bookTypeList.push(value);
        },
        ADD_BOOK(state, value) {
            state.bookList.push(value);
        }
    }

}